### ISSUE TITLE
automatic_feedback is broken

### ISSUE THREAD

**Issue by Bluesy1** [open-resources/problem_bank_helpers#33]
I think this is caused by commit https://github.com/open-resources/problem_bank_helpers/commit/8398a2343db8a89a329a90f4cee301f43bc4ff79:
```py
Python 3.11.3 (main, Jun 15 2023, 07:34:52) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import problem_bank_helpers as pbh
>>> example_data = {
...     "correct_answers": {"part1": 1},
...     "submitted_answers": {"part1": 1.0}
... }
>>> pbh.automatic_feedback(example_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gavin/.pyenv/versions/3.11.3/lib/python3.11/site-packages/problem_bank_helpers/problem_bank_helpers.py", line 273, in automatic_feedback
    data["feedback"][ans] = ErrorCheck(data['submitted_answers'][ans],
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ErrorCheck() missing 1 required positional argument: 'tolerance'
>>> 
```
I'm not sure the best way to fix this - I first noticed this when I had to make this commit to a Stats Bank draft question: https://github.com/open-resources/instructor_stats_bank/pull/245/commits/b783812ec2fba0f796cc6963c21ef47418dd9960
